### ISSUE TITLE
Python Code Execution

### ISSUE THREAD

**Issue by Btibert3** [wfondrie/pydeck#1]
I just came across this solution, and I am very excited as a user migrating from R.  Within the R ecosystem, we can use the xaringan library to build slide comparable slide decks, but they can include arbitrary R code that is executed when the deck is built.  Simply, if I say 2+2, I have the output 4 shown on the rendered deck, with an option to either show or hide the code that generated the result.  

This is the closest solution I have seen so far, but it's not clear if we can inject executed python code onto the rendered decks.  Is that possible or in the roadmap?

**Comment by wfondrie** [comment]
Thanks for your interest in pydeck. As of now (and probably the future), pydeck does not support code execution.

Originally I had intended for this project to provide similar functionality to xaringan, but for Python. However, after starting the project I've found two alternative solutions that work quite well: 

1. [RISE](https://rise.readthedocs.io/en/stable/) builds reveal.js slide decks out of Jupyter notebooks.
2. Using xaringan itself - You can directly execute Python code in an Rmarkdown document using [reticulate](https://rstudio.github.io/reticulate/articles/r_markdown.html)

Since these options exist, I've pretty much stopped development on this package.

**Comment by Btibert3** [comment]
Understood, thank you.  I am not the biggest fan of how the execution via
reticulate, as the development for is clunky in my opinion.  I will give
RISE a second look, but as you noted, I was really looking for the same
xaringan flow in python.

Thanks for the update, I appreciate it.
